version: "3.6"
services:
  mk-ghost:
    image: ghost:3.41.1-alpine
    container_name: mk-ghost
    restart: unless-stopped
    environment:
      - URL=http://cms.mkreg.local
      - NODE_ENV=production
    expose:
      - 2368
    volumes:
      - /var/lib/ghost/content:/var/lib/ghost/content
    networks:
      - mk

  mk-next:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile.next
    image: mk-next
    env_file:
      - ../../.env
    container_name: mk-next
    expose:
      - 3000
    restart: unless-stopped
    networks:
      - mk

  mk-nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    image: mk-nginx
    container_name: mk-nginx
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - mk

networks:
  mk:
