version: "3.6"
services:
  mk-next:
    build:
      context: ../
      dockerfile: docker/Dockerfile.next
    image: mk-next
    env_file:
      - ../.env
    container_name: mk-next
    depends_on:
      - mk-ghost
    expose:
      - 3000
    restart: unless-stopped
    networks:
      - mk_prod

  mk-nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    image: mk-nginx
    depends_on:
      - mk-ghost
      - mk-next
    container_name: mk-nginx
    restart: unless-stopped
    expose:
      - 80
      - 81
    networks:
      - mk_prod

  mk-proxy:
    build:
      context: ./haproxy
      dockerfile: Dockerfile.prod
    image: mk-proxy
    volumes:
      - ./ssl/cf/haproxy_ecc.pem:/etc/haproxy/ssl/haproxy_ecc.pem:ro
      - ./ssl/dh/dhparam-2048.pem:/etc/haproxy/ssl/dhparam-2048.pem:ro
      - ./cf_ips.lst:/etc/haproxy/cf_ips.lst
    depends_on:
      - mk-nginx
    container_name: mk-proxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    networks:
      - mk_prod

networks:
  mk_prod:

